# products/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from . import views
from .views import MyTokenObtainPairView # import JWT View

# 1. Initialize DRF Router
router = DefaultRouter()
# 2. Register the Product ViewSet (Creates /products/ and /products/<id>/ routes)
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    
    # path('', views.ProductViewSet.as_view({'get': 'list'}), name='products'), 
    
    # cart api url
    path('orders/add/', views.add_item_to_cart, name='add-item-to-cart'),

    # === authentification API ===
    # get JWT Token (log in API)
    path('users/login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    
    #get the info of the login users  API (for test purpose only)
    path('users/profile/', views.getUserProfile, name='users-profile'),
    
    # register API
    path('users/register/', views.registerUser, name='register'),
    #users may view their orders
    path('myorders/', views.getMyOrders, name='myorders'),
    # [FIX] Added 'orders/' prefix to prevent overlapping with 'products/' requests
    path('orders/<str:pk>/', views.getOrderById, name='user_order'),
    # --- DRF Router Routes (Attached to the App's root path) ---
    # This mounts all routes generated by the router (e.g., 'products/') at the current path.
    path('', include(router.urls)), 

]







