# Generated by Django 5.2.9 on 2026-01-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shippingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
    ]
