# Generated by Django 5.2.9 on 2026-01-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shipping_address',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_price',
            new_name='shippingPrice',
        ),
    ]
